'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import Sidebar from '@/components/Sidebar';
import { getToken, chatAPI } from '@/lib/api';

interface Message {
  id: number;
  role: 'user' | 'nexus';
  content: string;
  intent?: string;
  mission?: {
    id: number;
    title: string;
    tasks_count: number;
  };
  timestamp: Date;
}

export default function ChatPage() {
  const router = useRouter();
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const [messages, setMessages] = useState<Message[]>([
    {
      id: 1,
      role: 'nexus',
      content:
        "Hello! I'm NEXUS AI OS. Tell me what you want to build or accomplish, and I'll create a mission and execute it for you.\n\nExamples:\n• Create a marketing plan for my business\n• Build a social media strategy\n• Analyze my competitor landscape",
      timestamp: new Date(),
    },
  ]);

  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const token = getToken();
    if (!token) {
      router.push('/');
    }
  }, [router]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const sendMessage = async () => {
    if (!input.trim() || loading) return;

    const userMessage: Message = {
      id: Date.now(),
      role: 'user',
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setLoading(true);

    try {
      const response = await chatAPI.sendMessage(input.trim());

      const nexusMessage: Message = {
        id: Date.now() + 1,
        role: 'nexus',
        content: response.response,
        intent: response.intent,
        mission: response.mission,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, nexusMessage]);
    } catch {
      const errorMessage: Message = {
        id: Date.now() + 1,
        role: 'nexus',
        content: 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  return (
    <div className="flex min-h-screen bg-gray-950">
      <Sidebar />

      <main className="flex-1 flex flex-col">
        <div className="border-b border-gray-800 p-6">
          <h1 className="text-xl font-bold">NEXUS Command Center</h1>
          <p className="text-gray-400 text-sm mt-1">
            One Command. Infinite Execution.
          </p>
        </div>

        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex ${
                message.role === 'user' ? 'justify-end' : 'justify-start'
              }`}
            >
              <div
                className={`max-w-2xl rounded-2xl px-4 py-3 ${
                  message.role === 'user'
                    ? 'bg-blue-600 text-white'
                    : 'bg-gray-900 border border-gray-800 text-white'
                }`}
              >
                {message.role === 'nexus' && (
                  <div className="flex items-center gap-2 mb-2">
                    <div className="w-5 h-5 bg-blue-600 rounded flex items-center justify-center text-xs font-bold">
                      N
                    </div>
                    <span className="text-xs text-blue-400 font-medium">
                      NEXUS AI OS
                    </span>
                  </div>
                )}

                <div className="text-sm whitespace-pre-wrap">
                  {message.content}
                </div>

                {message.mission && (
                  <div className="mt-3 bg-gray-800 border border-gray-700 rounded-xl p-4">
                    <div className="text-xs text-green-400 font-medium mb-1">
                      ✅ Mission Created
                    </div>
                    <div className="font-semibold text-sm mb-1">
                      {message.mission.title}
                    </div>
                    <div className="text-xs text-gray-400 mb-3">
                      {message.mission.tasks_count} tasks generated by AI
                    </div>
                    <button
                      onClick={() =>
                        router.push(`/missions/${message.mission!.id}`)
                      }
                      className="bg-blue-600 hover:bg-blue-700 text-white text-xs px-3 py-1.5 rounded-lg transition-colors"
                    >
                      View Mission →
                    </button>
                  </div>
                )}

                <div
                  className="text-xs text-gray-500 mt-2"
                  suppressHydrationWarning
                >
                  {message.timestamp.toLocaleTimeString()}
                </div>
              </div>
            </div>
          ))}

          {loading && (
            <div className="flex justify-start">
              <div className="bg-gray-900 border border-gray-800 rounded-2xl px-4 py-3">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-5 h-5 bg-blue-600 rounded flex items-center justify-center text-xs font-bold">
                    N
                  </div>
                  <span className="text-xs text-blue-400 font-medium">
                    NEXUS AI OS
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce" />
                  <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce delay-100" />
                  <div className="w-2 h-2 bg-blue-500 rounded-full animate-bounce delay-200" />
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        <div className="border-t border-gray-800 p-4">
          <div className="flex gap-3 items-end">
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Tell NEXUS what you want to do... (Enter to send)"
              rows={2}
              className="flex-1 bg-gray-900 border border-gray-700 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-blue-500 resize-none text-sm"
            />
            <button
              onClick={sendMessage}
              disabled={loading || !input.trim()}
              className="bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 text-white px-5 py-3 rounded-xl transition-colors font-medium text-sm"
            >
              {loading ? '...' : '▶'}
            </button>
          </div>
          <p className="text-xs text-gray-600 mt-2">
            Press Enter to send • Shift+Enter for new line
          </p>
        </div>
      </main>
    </div>
  );
}